### ISSUE TITLE
Ambiguity within max_digits10 documentation?

### ISSUE THREAD

**Issue by acc987** [boostorg/multiprecision#104]
Within [...]tut/limits/constants.html#boost_multiprecision.tut.limits.constants.max_digits10 you state as of 1.69.0 the following: "For Microsoft Visual Studio before 2013, and default float format, a small range of values approximately 0.0001 to 0.004, with exponent values of 3F2 to 3F6, are wrongly input by one least significant bit, probably every third value of significand."

This statement is not quite clear to me and I would appreciate it if you could clarify the following and augment the documentation where applicable:
1. I am assuming that "values approximately 0.0001 to 0.004" refers to the decimal value of the significand?
2. I am assuming that the exponent, unlike the significand, is stated as a hexadecimal value?
3. The exponents (interpreted as hexadecimal values) are only representable in double precision. Does this issue exist for single-precision floating-point values, too?
4. Are you really meaning to say that it is "wrongly input"? Or do you rather mean that it is wrongly output?

As I am very interested in floating-point to decimal conversion (and vice-versa) in older versions of Visual Studio myself, is there any further documentation available regarding this issue? I noticed that the documentation above was initially introduced with boost release 1.56 and the information that VS2013 and greater is not affected was added with 1.60, but I was not able to find further information or examples that demonstrate the problem.

**Comment by acc987** [comment]
Dear Paul,

thank you for your reply. I tried to reworked the parts, which I perceive as ambiguous, and ended up with the following patch: https://gist.github.com/acc987/aca5e46ccbfb3ca11b5777b90616dfaa.

Do you agree with my proposed changes? It seems like you were involved when this note in the documentation was created, so if you agree with my changes, feel free to create a pull request. Otherwise I would create the request if the changes are OK with you.

If it is not too much trouble for you, I would indeed be interested in trying out your reproducer code for myself.

**Comment by pabristow** [comment]
That looks very slightly clearer if you feel this is worthwhile I'll accept a pull request.

But it seems of largely historical interest only as all currrent GCC, Clang and MSVC compilers finally get it almost all right now.  Rick Regan writes authoritively at https://www.exploringbinary.com/maximum-number-of-decimal-digits-in-binary-floating-point-numbers/ on this surprisingly difficult subject.  I think you should digest what he says fully before experimenting further.  There is also a new algorithm at https://arxiv.org/pdf/1310.8121.pdf which I believe is already in use by several compilers, so the inaccuracies discovered are truely history.

**Comment by jzmaddock** [comment]
Paul, did you intend to reopen this?

**Comment by pabristow** [comment]
Yes, but to ADD further info and links on more recent algorithms, keeping the PR.

I suspect I havemis-GITed.  What should I do to rectify this?

**Comment by jzmaddock** [comment]
These changes will be in the next release, any reason not to close?

**Comment by acc987** [comment]
Dear John,

it looks to me like Paul added his comments directly within the documentation with commit 136f71893547faa56353954e76181b6d39db7c8f. I am thus taking the liberty of closing this issue, since a new boost version has been released on 2019-04-12.
