### ISSUE TITLE
shift by multiprecision

### ISSUE THREAD

**Issue by ohhmm** [boostorg/multiprecision#105]
`arbitrary = arbitrary << arbitrary_too;`

Invalid operands to binary expression ('omnn::math::Integer::base_int' (aka 'number<cpp_int_backend<> >') and 'const omnn::math::a_int' (aka 'const number<cpp_int_backend<> >'))

**Comment by jzmaddock** [comment]
That's deliberately not supported - I couldn't think of a use case where shifting by a multiprecision type made any sense - since any conceivable shift value can be stored in a std::size_t.
Do you have a use case in mind?

**Comment by ohhmm** [comment]
the case is not using numeric_cast for the operand
