### ISSUE TITLE
sqrt

### ISSUE THREAD

**Issue by ohhmm** [boostorg/multiprecision#106]
boost::multiprecision::cpp_int i = 32;
    auto sq = boost::multiprecision::sqrt(i);
    BOOST_TEST(sq*sq==i); // fails

**Comment by jzmaddock** [comment]
Of course that fails - sqrt on integer types performs integer square-root which in this case is 5, and 5*5 != 32.
In case you're wondering integer square root is important for certain number-theoretic algorithms, including implementing floating-point square root.
