### ISSUE TITLE
serialization does not support xml archives

### ISSUE THREAD

**Issue by HDembinski** [boostorg/multiprecision#111]
I am using cpp_int in Boost.Histogram. @swatanabe asked me to support serialization to xml archives in his review. For that I need cpp_int to be xml-serializable. This looks like only text and binary archives are supported:
https://github.com/boostorg/multiprecision/blob/develop/include/boost/multiprecision/cpp_int/serialize.hpp
Can this be implemented?

**Comment by jzmaddock** [comment]
What do I need to do?

I thought that once the type was serializable it was agnostic of the archive type?

**Comment by HDembinski** [comment]
Basically, instead of `ar & my_variable` you need to do `ar & make_nvp("my_variable", my_variable)` everywhere. See https://www.boost.org/doc/libs/1_67_0/libs/serialization/doc/wrappers.html, section "Name-Value Pairs".

**Comment by jzmaddock** [comment]
Closing in favor of referenced PR.
