### ISSUE TITLE
-Wpedantic warning in develop branch

### ISSUE THREAD

**Issue by HDembinski** [boostorg/multiprecision#116]
../../boost/multiprecision/detail/number_base.hpp:1558:24: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
 struct number_category<__int128> : public mpl::int_<number_kind_integer> {};

**Comment by jzmaddock** [comment]
Fixed in develop.

**Comment by HDembinski** [comment]
Thank you! :+1:
