### ISSUE TITLE
Incorrect information in the tutorial/example

### ISSUE THREAD

**Issue by hashangayasri** [boostorg/multiprecision#117]
The example in 

> multiprecision/doc/html/boost_multiprecision/tut/ints/cpp_int.html
> <https://www.boost.org/doc/libs/1_69_0/libs/multiprecision/doc/html/boost_multiprecision/tut/ints/cpp_int.html> 

has misleading/incorrect comments. The actual outputs are:
`2432902008176640000`
and
`93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000`

**Comment by pabristow** [comment]
Confirmed.  I think we could make this a bit clearer (especially by using the actual output as a snippet). On my TODO list.

**Comment by jzmaddock** [comment]
The comments are correct though, what it says is:

```
// prints 20!
```

And 20! = 2432902008176640000 etc.

**Comment by jzmaddock** [comment]
Will be corrected for the next release.
