### ISSUE TITLE
Assertion error in eval_exp (transcendental.hpp)

### ISSUE THREAD

**Issue by kedarbhat** [boostorg/multiprecision#120]
Since I can't delete this blank comment, I'll use the space.

The error below is with latest Boost 1.70. I'm not sure yet if this occurs in earlier versions.

**Comment by kedarbhat** [comment]
I think this may be similar/related to issue #23. The below code (using `boost::multi precision::cpp_bin_float_50`) fails an invariant in `eval_exp` (in transcendental.hpp). The computation using `double` as the type is included to verify it's a valid computation. This seems to happen when `boost::math::zeta` is instantiated with `boost::multi precision::cpp_bin_float_50`. 

```
BOOST_AUTO_TEST_CASE(multiprecision_zeta) {
  using T = boost::multiprecision::cpp_bin_float_50;
  static constexpr auto x = 2.0;
  static constexpr auto y = 95.0;
  T x_mp(x);
  T y_mp(y);
  auto answer = std::exp(y*std::log(x));
  BOOST_REQUIRE_CLOSE(answer, 3.9614081257131865e28, std::numeric_limits<T>::epsilon());
  auto answer_mp = boost::math::zeta(boost::multiprecision::exp(y_mp*boost::multiprecision::log(x_mp)));
  BOOST_REQUIRE_CLOSE(answer, answer_mp, std::numeric_limits<T>::epsilon());
}
```

**Comment by jzmaddock** [comment]
Fixed in develop.

**Comment by kedarbhat** [comment]
Thanks for the quick turnaround!
