### ISSUE TITLE
String output does not respect uppercase flag for hexadecimal base prefix

### ISSUE THREAD

**Issue by pavelkryukov** [boostorg/multiprecision#129]
Consider following program:

```c++
#include <cstdint>
#include <boost/multiprecision/cpp_int.hpp>

int main()
{
    uint64_t val64 = 0xf;
    boost::multiprecision::uint128_t val128 = 0xf;
    std::cout << std::hex << std::uppercase << std::showbase
              << "uint64: "  << val64 << std::endl
              << "uint128: " << val128 << std::endl;
    return 0;
}
```

The output is:
```
uint64: 0XF
uint128: 0xF
```

The expected output is (note the uppercase for `0x`):
```
uint64: 0XF
uint128: 0XF
```

**Comment by KingBodo** [comment]
> Consider following program:
> 
> ```c++
> #include <cstdint>
> #include <boost/multiprecision/cpp_int.hpp>
> 
> int main()
> {
>     uint64_t val64 = 0xf;
>     boost::multiprecision::uint128_t val128 = 0xf;
>     std::cout << std::hex << std::uppercase << std::showbase
>               << "uint64: "  << val64 << std::endl
>               << "uint128: " << val128 << std::endl;
>     return 0;
> }
> ```
> 
> The output is:
> 
> ```
> uint64: 0XF
> uint128: 0xF
> ```
> 
> The expected output is (note the uppercase for `0x`):
> 
> ```
> uint64: 0XF
> uint128: 0XF
> ```
