### ISSUE TITLE
Add float128 support for MSVC/Clang?

### ISSUE THREAD

**Issue by sdcb** [boostorg/multiprecision#13]

**Comment by jzmaddock** [comment]
How?

Neither compiler supports __float128 as far as I know.

The closest alternative would be to use cpp_bin_float_quad which provides the same functionality, albeit all in software and a lot slower.

**Comment by sdcb** [comment]
Yeah, cpp_bin_float_quad is what I mean. is there any performance comparison for float128 and cpp_bin_float_quad?

**Comment by jzmaddock** [comment]
On 24/11/2015 12:52, sdflysha wrote:
>
> Yeah, cpp_bin_float_quad is what I mean. is there any performance 
> comparison for float128 and cpp_bin_float_quad?
>

Not really but I just ran the linpack benchmark for each and came up with:

double:                                               2727 MFlops
__float128:                                              35MFlops
multiprecision::float128:                       35MFlops
multiprecision::cpp_bin_float_quad:     6MFlops
