### ISSUE TITLE
cpp_int wrong static_assert

### ISSUE THREAD

**Issue by truedim** [boostorg/multiprecision#145]
Tried to use boost::multiprecision::cpp_int with WebAssembly clang compiler (v9)
It produces 32 bit code and BOOST_HAS_INT128 is correctly defined.
**sizeof(boost::multiprecision::limb_type) = 8** due to BOOST_HAS_INT128
**sizeof (limb_data)=8** because it is a struct with two 32 bit members

**internal_limb_count=sizeof(limb_data) / sizeof(limb_type)=1**

compilation of my project failed: cpp_int.hpp, line 1236
```cpp
BOOST_STATIC_ASSERT(base_type::internal_limb_count >= 2); 
```

**Comment by jzmaddock** [comment]
This works for me with emcc (which appears not to support __int128), what compiler and command line are you using?

**Comment by truedim** [comment]
> This works for me with emcc (which appears not to support __int128), what compiler and command line are you using?

Yes, it works with the current Fastcomp backend (LLVM 6.0), but it fails with the new LLVM upstream backend: [https://v8.dev/blog/emscripten-llvm-wasm](https://v8.dev/blog/emscripten-llvm-wasm)

**Comment by jzmaddock** [comment]
Still not getting it.  I have:

```
#include <boost/multiprecision/cpp_int.hpp>

static_assert(sizeof(boost::multiprecision::limb_type) == 8, "Oops");

int main(int argc, char **argv) 
{
   boost::multiprecision::cpp_int i(23);
   i << 400;
   boost::multiprecision::uint128_t a(2);
   boost::multiprecision::uint256_t b(2);
   boost::multiprecision::uint512_t c(2);
}
```
and
```
jzm@jzm-vm:~/boost/boost$ $EMSDK/upstream/emscripten/em++ --version
emcc (Emscripten gcc/clang-like replacement) 1.38.39 (commit a51302ba20697f5251a8185cfdc72e72b14351e4)
```

Which builds just fine.

**Comment by truedim** [comment]
I can confirm, that your example builds fine, but it fails if your add the following line to the end of main:
  
`std::cout<<i<<std::endl;`
