### ISSUE TITLE
Multiprecision floating point types don't register as such with std

### ISSUE THREAD

**Issue by kshegunov** [boostorg/multiprecision#156]
Hello,
The following typedef:
```
using namespace boost::multiprecision;
typedef number<backends::cpp_bin_float<2048, backends::digit_base_2, void, boost::int32_t, -32766, 32767>, et_off> floatx;
```

Doesn't register as a floating point type with std, i.e. `std::is_floating_point<floatx>::value` is `false`. It may not be truly easy to implement, but I do expect them to define the `std::is_floating_point< ... >::value` constant as true, do I miss something here?

**Comment by ckormanyos** [comment]
I believe that std::is_floating_point<T>::value is only true if T is of built-in type float, double or long double. Apparantly, this is not specified for user-defined floating-point types, as the type cpp_bin_float is a user-defined type.

Best regards, Chris

**Comment by jzmaddock** [comment]
Chris is correct, type_traits tells you about what kind of type it is (it's a class type and not a fundamental type).  If you want to know about it's behaviour, use std::numeric_limits.

**Comment by kshegunov** [comment]
Fair enough.
Thanks for looking into it!
