### ISSUE TITLE
Problem using float128 with odeint

### ISSUE THREAD

**Issue by cffk** [boostorg/multiprecision#159]
Starting with boost 1.68.0, there's been a problem compiling an odeint program which uses the float128 type.  Since there were no changes in the odeint package between boost 1.67.0 and 1.68.0, I suspect the multiprecision library.  Details are in https://github.com/boostorg/odeint/issues/40

**Comment by cosurgi** [comment]
Most of the discussion happens in https://github.com/boostorg/odeint/issues/40
