### ISSUE TITLE
Boost.Integer test failures on clang-9 in C++03 mode

### ISSUE THREAD

**Issue by Lastique** [boostorg/multiprecision#163]
See here:

https://travis-ci.org/boostorg/integer/jobs/601250569#L774

There are multiple problems:

1. Using unified initialization syntax in https://github.com/boostorg/multiprecision/blob/f59ac5056e93872849df701b9a55010bc367a64c/include/boost/multiprecision/cpp_int.hpp#L474 without a check for `BOOST_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX`.
2. Using `constexpr` in https://github.com/boostorg/multiprecision/blob/f59ac5056e93872849df701b9a55010bc367a64c/include/boost/multiprecision/cpp_int.hpp#L532 and several other places instead of `BOOST_CONSTEXPR`.
3. Using `constexpr` in https://github.com/boostorg/multiprecision/blob/f59ac5056e93872849df701b9a55010bc367a64c/include/boost/multiprecision/cpp_int/bitwise.hpp#L622 instead of `BOOST_CONSTEXPR_OR_CONST`.

Maybe there are more problems, the above ones are those made immediately apparent by Boost.Integer test failures.

**Comment by jzmaddock** [comment]
Reproduced.

The sections of code you highlight **are** guarded for the presence of the C++20 feature `std::is_constant_evaluated()`, but apparently clang's __has_builtin is signalling the presence of the feature even in C++03 :(

Testing fix now.

**Comment by jzmaddock** [comment]
This should be fixed in release now
