### ISSUE TITLE
header self-sufficience test

### ISSUE THREAD

**Issue by ohhmm** [boostorg/multiprecision#171]
self sufficient header is a header which requires no other headers to be included before the header.
the example of an introduced issue because of introduced header non-self-sufficiency is multiprecision/roots.hpp in 1.70
an automated test of boost headers self-sufficiency would scan all boost headers and compile its inclusion lines. if compilation successful then the header test passed well.

**Comment by jzmaddock** [comment]
Duplicates #179.
