### ISSUE TITLE
Dangling reference in expressions

### ISSUE THREAD

**Issue by spoofedex** [boostorg/multiprecision#175]
Hi all,

I've had a problem with code resembling the following crashing when compiling in release mode:
```
  namespace mp = boost::multiprecision;
  const auto value1  = mp::pow(mp::cpp_int(a), b);
  const auto value2  = mp::pow(mp::cpp_int(c), d);
  return value1 <= value2;
```

The cause seems to be that multiprecision's "pow" takes const references to the first parameter, which is passed (as reference) to "detail::expression", which stores it as a expression_storage_base<...>::type, which is a reference to the type in case of a cpp_int.

So "value1" contains a reference to the temporary, which is destroyed immediately. The comparison evaluates the expression, which causes the crash caused by the dangling reference.

This issue can be worked around by manually extending the lifetime of the cpp_int.

My recommendation would be to accept rvalue-references, and moving them to the storage. Otherwise, I'd say that an "= delete" of an overload that takes an rvalue-reference and documentation of the behaviour (if it does not yet exist; I could not find it) would be appropriate.

What are your thoughts? Thanks in advance!

**Comment by pabristow** [comment]
As this item
[https://stackoverflow.com/questions/40952097/strange-boost-cpp-int-behaviour-when-using-auto-type-deduction](url)  says, quoting the Boost.Multiprecision manual

The Boost introduction 
[https://www.boost.org/doc/libs/1_72_0/libs/multiprecision/doc/html/boost_multiprecision/intro.html](url)

even specifically mentions the pitfall of using auto to store an expression template

Expression templates can radically reorder the operations in an expression, for example: 
a = (b * c) * a; 
Will get transformed into: 
a *= c; a *= b; 
If this is likely to be an issue for a particular application, then expression templates should be disabled. 

Patient: Doctor, Doctor, I get garbage when I use auto and expression templates. together.
Doctor: Don't do that!

**Comment by jzmaddock** [comment]
>Patient: Doctor, Doctor, I get garbage when I use auto and expression templates. together.
Doctor: Don't do that!

This is true, however in this particular case, we can probably fix this.

BTW, elsewhere we've been updating our performance results, and expression templates appear to have questionable benefits for the latest crop of compilers.  It still needs more investigation, but you *may* find your code runs faster with expression templates turned off.

**Comment by ckormanyos** [comment]
> It still needs more investigation, but you may find your code runs faster with expression templates turned off.

Nod. My personal experience has shown very little or almost no significant *speed* differences resulting from ET either on/off.
