### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by Milerius** [boostorg/multiprecision#177]
https://github.com/boostorg/multiprecision/blob/632f68400c28e85d62171c40b16d71699ac6dfd7/include/boost/multiprecision/number.hpp#L2137

according to https://www.viva64.com/en/w/v739/ this is dangerous.

**Comment by ckormanyos** [comment]
John, what's your opinion on this?
I agree with the report. I could try for a fix for 1.73 if you like?

**Comment by ckormanyos** [comment]
I think meant 1.74 I believe, later in the future.

**Comment by madhur4127** [comment]
I think fix suggested in article itself is quite straightforward - change type of `c` to `int`. Also `peek()` returns `int` so `static_cast` should be risky.

**Comment by jzmaddock** [comment]
+1 on changing char to int, though to be honest the chances of hitting the issue when parsing *numbers* is probably vanishingly small?

**Comment by Milerius** [comment]
It is true that the problem is unlikely to occur, however it is better to prevent. Now that we know that there is a potential bug even if it is unlikely to happen better to solve it.

**Comment by borisssoft** [comment]
@ckormanyos Fixed in https://github.com/boostorg/multiprecision/commit/9e7fc3077c663c0cfc19fa40aab41cacf62417d7

**Comment by ckormanyos** [comment]
Thanks @borisssoft. Closed.
