### ISSUE TITLE
An attempt to make Boost.Multiprecision docs more user friendly

### ISSUE THREAD

**Issue by pabristow** [boostorg/multiprecision#192]
I have fretted that the Boost.Multiprecision Docs don't seem easy to get started
(unashamedly pandering to the users who 'just want more bits' - a significant potential user group).
Novice users do not need to get frightened (perhaps frightened-off!) by front- and back- ends or expression templates,
So I have done some work trying to reduce the steepness of the learning curve, adding many internal and external hyper-links to make navigation easier,
and a new example warning of the difference between fundamental_types and multiprecision 'dropins'.

(En route I have tried to resolve lots of minor editorial matters like typos (I swear that they breed), grammar, spelling, punctuation, compielr warnings etc.)

My best efforts so far are in a new branch from develop/multiprecision called docs_update_1.
Maybe some time you can glance and see if you think this is an improvement.

**Comment by madhur4127** [comment]
There are also subtleties like fixed precision really means a backend without allocator and has nothing to do with the bits.

This caused confusion because I initially thought fixed precision implies a backend with `MinBits==MaxBits` much of which arises from these lines in the documentation.

```cpp
// Fixed precision unsigned types:
typedef number<cpp_int_backend<128, 128, unsigned_magnitude, unchecked, void> >   uint128_t;
typedef number<cpp_int_backend<256, 256, unsigned_magnitude, unchecked, void> >   uint256_t;
typedef number<cpp_int_backend<512, 512, unsigned_magnitude, unchecked, void> >   uint512_t;
typedef number<cpp_int_backend<1024, 1024, unsigned_magnitude, unchecked, void> > uint1024_t;
....
// Fixed precision signed types:
typedef number<cpp_int_backend<128, 128, signed_magnitude, checked, void> >       checked_int128_t;
typedef number<cpp_int_backend<256, 256, signed_magnitude, checked, void> >       checked_int256_t;
typedef number<cpp_int_backend<512, 512, signed_magnitude, checked, void> >       checked_int512_t;
typedef number<cpp_int_backend<1024, 1024, signed_magnitude, checked, void> >     checked_int1024_t;
```

**Comment by jzmaddock** [comment]
I've made this a draft PR as I couldn't seem to comment on the changes in the branch where as I can in the PR.  See https://github.com/boostorg/multiprecision/pull/193.

Thanks!

**Comment by ckormanyos** [comment]
Can this issue be closed?
Were all points handled in #193
Thanks!

**Comment by pabristow** [comment]
I believe all in current develop now, so yes.  I think John (who created it as a PR from the branch) needs to close it?

Paul
