### ISSUE TITLE
The floating_point_examples test requirement

### ISSUE THREAD

**Issue by eldiener** [boostorg/multiprecision#219]
For the floating_point_examples.cpp test you have the requirement:

`<toolset>gcc-mingw:<cxxflags>-Wa,-mbig-obj`

but gcc-mingw is not a toolset, although maybe it once was. I tried instead:

`<toolset>gcc/<target-os>windows:<cxxflags>-Wa,-mbig-obj`

but despite compiling with mingw-w64/gcc on Windows the -Wa,-mbig-obj was not being set, so I do not know what should work in that case. Of course if I add to my user-config.jam for gcc on Windows a <cxxflags>-Wa,-mbig-obj then it gets picked up from there, but I do not know how to get it picked up from your test requirement. However even when it does get picked up the mingw-w64/gcc-9.3 compiler still gives errors from the assembly. What can one expect on Windows <g>.

**Comment by eldiener** [comment]
What do you mean by 'And it does the business for this application, so I’m not clear why it doesn’t work for you.' ?

If I run:

b2 toolset=gcc-9.3 etc.

it does not think that this is 'gcc-mingw', whatever that is supposed to mean, despite the fact that the gcc is on Windows and is a mingw-w64/gcc-9.3 implementation. It does in the gcc.jam file identify my gcc as mingw using its internal logic, and it does configure gcc with my user-config.jam statement of:

using gcc : 9.3 : 
    "my_path/my_command_etc" :
    <cxxflags>-Wno-unused-local-typedefs 
    <cxxflags>-ftrack-macro-expansion=0 
    <cxxflags>-Wno-unused-variable 
    <cxxflags>-D_GLIBCXX_USE_CXX11_ABI=1 
    <root>"c:/Utilities/mingw-w64/x86_64-9.3.0-posix-seh-rt_v7-rev0/mingw64"
    ;

correctly.

BTW, since you asked, I am building gcc-9.3 on Windows using MSYS2 from the implementation at https://github.com/niXman/mingw-builds . It has worked perfectly fine for me. I recomnmend it.

Again I have no idea what gcc-mingw is supposed to mean. This should either be a toolset, like 'clang-win' or 'clang-linux' with its own jam file in Boost Build, or it should be some subfeature of the gcc toolset, which does exist as 'gcc.jam'. But there is no Boost Build jamfile called 'gcc-mingw.jam' and I do not see a subfeature of gcc called mingw anywhere. Maybe you are right and Boost Build does some sort of "magic" to associate 'gcc-mingw' with gcc running on Windows using mingw(-w64)/gcc, but I would really like to know what this "magic" is since it clearly is not working for me.

**Comment by eldiener** [comment]
I asked on the Boost.Build list.

Thanks for the heads up on using quadmath.

Are you sure that with your toolset definition for 10.0.1 that '-Wa,-mbig-obj' is being added to the command line when running the 'floating_point_examples.cpp test' ? Try adding '-d2" to your b2 invocation to find out.

**Comment by jzmaddock** [comment]
It's not working for me either - though it used to.

I think the best way to fix this may be to write a short test to check whther that command line option is supported and use [ check-target-builds ] to add the option when supported.

**Comment by jzmaddock** [comment]
Should be fixed in https://github.com/boostorg/multiprecision/pull/221
