### ISSUE TITLE
Fixed point arithmetic

### ISSUE THREAD

**Issue by NAThompson** [boostorg/multiprecision#238]
Are there any backends that support fixed point arithmetic?

**Comment by jzmaddock** [comment]
No, not yet.

**Comment by ckormanyos** [comment]
>> Are there any backends that support fixed point arithmetic?
> No, not yet.

@johnmcfarlane has done some fascinating work in this area with [cnl](https://github.com/johnmcfarlane/cnl)

We also made a serious effort during Boost GSoC 2015 [fixed-point](https://github.com/BoostGSoC15/fixed_point)

In the GSoC '15 work, we had a difference of opinion with some other experts regarding certain technical issues. Other than that, the `negatable` class from the GSoC 2015 experience has some really cool fixed-point code. I still use it _on the metal_ in  embedded systems.

It would really only take a good few weeks to adapt some of that code for a legit backend for multiprecision, and I think we should mark fixed-point backend as a potential enhancement (GSoC' 21 maybe).

**Comment by NAThompson** [comment]
Thanks guys; useful info.
