### ISSUE TITLE
H0F1 Failed to converge

### ISSUE THREAD

**Issue by NAThompson** [boostorg/multiprecision#24]
The following code:

    int main()
    {
        using std::cos;
        auto z = boost::lexical_cast<boost::multiprecision::cpp_bin_float_quad>("830758237335105368403462033753302704124887023084254016541868647823752047904229528199808155648");
        std::cout << cos(z) << std::endl;
    }

results in the following error message:

```
../multiprecision/include/boost/multiprecision/detail/functions/trig.hpp(69): fatal error: in "void boost::multiprecision::default_ops::hyp0F1(T&, const T&, const T&) [with T = boost::multiprecision::backends::cpp_bin_float<113u, (boost::multiprecision::backends::digit_base_type)2u, void, short int, -16382, 16383>]": boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >: H0F1 Failed to Converge
```

Reproduced with `g++ 6.3` and `clang 4.0`.

**Comment by jzmaddock** [comment]
OK, I see the issue: the value is so large that after argument reduction 
you're left with garbage.

I have a trivial fix, but I guess the open question is what value should 
be returned in this situation?  My fix involves assuming that argument 
reduction in this situation yields zero, so cos(some_big_number) always 
returns 1.  std::cos appears to return garbage, and there's nothing in 
C99 to specify a convention as far as I can see?

Thanks for the report, John.

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by NAThompson** [comment]
So your fix would ostensibly be something like?

    if (abs(theta)*std::numeric_limits<Real>::epsilon() > 1) // Domain reduction must return garbage
    {
        return 1; // Some sensible value that doesn't halt the computation.
    }

I think that's sensible, but it looks as if <a href="https://www.csee.umbc.edu/~phatak/645/supl/Ng-ArgReduction.pdf">Kahan</a> has given an algorithm for accurate evaluation of trig functions at huge arguments. Maybe a todo entry?

**Comment by jzmaddock** [comment]
Mostly fixed in here: https://github.com/boostorg/multiprecision/commit/f2a266da6d1af62653ccd88c444dad880d31b998

Correct handling of huge arguments, Kahan style, will have to wait for now.
