### ISSUE TITLE
max_digits10 + mpfr hangs

### ISSUE THREAD

**Issue by NAThompson** [boostorg/multiprecision#245]
In the representations [PR](https://github.com/boostorg/multiprecision/pull/244), we get a hang unless we comment out

```cpp
out << std::setprecision(std::numeric_limits<Real>::max_digits10);
```

`cpp_bin_float` does not hang . . .

**Comment by jzmaddock** [comment]
That's weird, it's just an integer constant with value INT_MAX for `mpfr_float`.  Can you preprocess the source and make sure that the definition for numeric_limits<>::max_digits10 is in the output?  Should be mpfr.hpp:2614, but is conditional on `BOOST_NO_INCLASS_MEMBER_INITIALIZATION` (which should *not* be set in the cases you mention).

**Comment by jzmaddock** [comment]
Oh.... sorry, I see the issue, you're setting the precision of the stream to INT_MAX.  The issue is that there is no sane value for this constant for variable precision types?

**Comment by NAThompson** [comment]
As a workaround, I have the following:

```
    constexpr int p = std::numeric_limits<Real>::max_digits10;
    out << std::setprecision(p);
    if constexpr (p == 2147483647) {
        out << std::setprecision(rep.x_.backend().precision());
    }
```
