### ISSUE TITLE
Setting precision in gmp_int is undocumented.

### ISSUE THREAD

**Issue by NAThompson** [boostorg/multiprecision#258]
See [here](https://www.boost.org/doc/libs/1_73_0/libs/multiprecision/doc/html/boost_multiprecision/tut/ints/gmp_int.html).

**Comment by jzmaddock** [comment]
?  You don't/can't set it's precision, it's a variable/infinite precision type.

**Comment by NAThompson** [comment]
@jzmaddock : Then I'm a bit confused about its behavior; it saturated on conversion from `mpfr` types to the `int64_t` max. In any case, I can't reproduce since now I'm hitting the following:

```
#include <boost/multiprecision/mpfr.hpp>
#include <boost/multiprecision/gmp.hpp>

int main() {
    using boost::multiprecision::gmp_int;
    
    using boost::multiprecision::mpfr_float;
    mpfr_float::default_precision(1024);
    mpfr_float four = 4;
    gmp_int g = static_cast<gmp_int>(four);
}
```

Is this expected to work?

**Comment by jzmaddock** [comment]
gmp_int is the backend type: change it to mpz_int and it does work ;)
