### ISSUE TITLE
small problem with boost::multiprecision::frexp for MPFR only.

### ISSUE THREAD

**Issue by cosurgi** [boostorg/multiprecision#265]
Try this code:

```
#include <boost/multiprecision/mpfr.hpp>
#include <iostream>

int main()
{
	boost::multiprecision::mpfr_float_500 val("-0.999999999999999999999999778370088952043740344504867972909872539207515981285392968364222963125347205961928119872988781594713043198125331291");
	int b=0;
	std::cout << std::setprecision(80) << boost::multiprecision::frexp(val,&b) << "\n";
}
```

you will get:

```
-0.49999999999999999999999988918504447602187017225243398645493626960375799064269648
```

The problem is that frexp promises in specification to return value between [0.5 and 1](https://en.cppreference.com/w/cpp/numeric/math/frexp):

> if no errors occur, returns the value x in the range (-1;-0.5], [0.5; 1)

And I needed to write a code which depends on this promise. So for now I had to implement a simple workaround:

```
    // in here the norm is positive always.
    if ((norm > 0.25) and (norm < 0.5)) { // if this bug becomes more annoying this fix might need to get moved into MathFunctions.hpp
        norm *= 2;
        exponent -= 1;
    }
```

Complete code for this part is here: https://gitlab.com/yade-dev/trunk/-/blob/bitCorrectness/py/high-precision/_RealHPDiagnostics.cpp#L50

honestly I'm not sure if I should submit it here or to MPFR :) maybe both?

**Comment by jzmaddock** [comment]
My bad.  I'm using the wrong mpfr function I think.

**Comment by jzmaddock** [comment]
Fixes in https://github.com/boostorg/multiprecision/pull/266.

**Comment by jzmaddock** [comment]
Merged.
