### ISSUE TITLE
mpfr_float comparisons

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/multiprecision#302]
Should probably NOT be noexcept.

There are also native comparisons available for more types (float, double etc).

**Comment by anishsingh935** [comment]
Hi  can you please explain this issue ,exactly what is bug

**Comment by jzmaddock** [comment]
Ooops, this was fixed in https://github.com/boostorg/multiprecision/pull/303.

The bug was that the comparison operators for mpfr_float were marked as noexcept, and in general we can't guarantee that is the case since we don't know what mpfr is doing internally.
