### ISSUE TITLE
Drone CI Failures with Hash Replacement

### ISSUE THREAD

**Issue by mborland** [boostorg/multiprecision#310]
GHA and CircleCI are both green now, but it looks like there are still some failures in the Drone run from the hash replacement. Investigating.

**Comment by mborland** [comment]
So far I have only been able to replicate the errors using gnu++20. 11,14, and 17 all pass locally. Interestingly the drone runs configured for GCC10 actual provide 9.3.0; I am testing with 10.2.1.

**Comment by jzmaddock** [comment]
Line #635 of float128.hpp is going into infinite recursion.  Missing #include for overloads of hash_value maybe?

**Comment by mborland** [comment]
It looks like an ADL failure. I am testing this right now:

```
inline std::size_t hash_value(const float128_backend& val)
{
   return boost::multiprecision::detail::hash_value(static_cast<double>(val.value()));
}
```

**Comment by mborland** [comment]
Drone and CircleCI are both good now. Closing.
