### ISSUE TITLE
number<debug_adaptor<gmp_rational>> can't be constructed from number<debug_adaptor<gmp_int>> numerator and denominator

### ISSUE THREAD

**Issue by rulatir** [boostorg/multiprecision#329]
As per subject, the numerator/denominator constructor of a `number<debug_adaptor<gmp_rational>>` does not accept arguments of type `number<debug_adaptor<gmp_int>>`. This necessitates jumping through a lot more hoops than should be necessary if one wants to write code that will use wrapped or naked backends depending on the `DEBUG` preprocessor variable.

**Comment by jzmaddock** [comment]
Confirmed, all the "component-based" number types (rationals, complex, intervals) are basically broken with the logged/debug_adaptor.

Working on fixes now.
