### ISSUE TITLE
conversion to nearest float

### ISSUE THREAD

**Issue by afabri** [boostorg/multiprecision#360]
While the [documentation ](https://www.boost.org/doc/libs/1_77_0/libs/multiprecision/doc/html/boost_multiprecision/tut/conversions.html)states that exact rationals are rounded to nearest when converted to a floating point number, we observed with clang on Apple that this is only true if the rounding mode is set to nearest, as can be seen on [gist.github.com](https://gist.github.com/danston/91f74dfe3b9f6fbf3ba9c3d8920d8343).    This should maybe be made explicit in the manual, or the rounding code should be set as needed internally.
We didn't investigate yet how that is for VC++, and we only observed it for `cpp_int`.

**Comment by afabri** [comment]
When I change the rounding mode for VC++  with  `  unsigned int dummy; _controlfp_s(&dummy, _RC_UP, _MCW_RC);`  I do not encounter the problem, but maybe this only does not happen for this particular number.

**Comment by johnmcfarlane** [comment]
Under what circumstances is it desirable to change the rounding mode? It's this a common thing to do?
