### ISSUE TITLE
Rational to double conversion

### ISSUE THREAD

**Issue by leoneifler** [boostorg/multiprecision#361]
While comparing the use of multiprecision rationals using the gmp backend and directly using gmp, I noticed that the multiprecision library does not use `mpq_get_d` to convert to double (in `gmp.hpp`), rather it uses `generic_convert_rational_to_float` with the comment that `mpq_get_d` "does not round correctly".

Does anyone have more insight into how this incorrect rounding looks like? It seems that using the built-in `mpq_get_d` is quite a bit faster.

**Comment by jzmaddock** [comment]
Thanks @mglisse , closing for now, please reopen if there's a better solution.
