### ISSUE TITLE
Equivalent to mpz_scan1()

### ISSUE THREAD

**Issue by afabri** [boostorg/multiprecision#378]
Is there a high level function to find the index of the first non zero bit like  [ mpz_scan1()](https://gmplib.org/manual/Integer-Logic-and-Bit-Fiddling) ?

**Comment by jzmaddock** [comment]
msb and lsb (most/least significant bit) will do that.

**Comment by jzmaddock** [comment]
>I do not really get the argument. Does lsb() not also give us the least significant bit in a canonical representation and not in the implemented representation?

lsb also refuses to work on negative values.  I'm not sure that a "canonical representation" exists: IMO you could make a good case either way for that being 2's complement or signed-magnitude.

**Comment by afabri** [comment]
But what about `bit_test()` then.  Do  I get a true that depends on the representation?
