### ISSUE TITLE
Compile error when using std::is_copy_constructible with cpp_int

### ISSUE THREAD

**Issue by tzubcic-tolar** [boostorg/multiprecision#383]
Happens with clang 11.0 and newer when using libstdc++. Example here: https://godbolt.org/z/bWxTaETdW

I haven't digged much into the cause for this, but if it helps, user pdimov on cpplang slack suggested that this is probably some kind of constraint recursion and that `operator T()` needs an additional constraint that `T` is not `self_type`.

**Comment by jzmaddock** [comment]
It's the -std=c++17 switch that causes the issue, and it's a recursive dependency on is_constructible: both is_copy_constructible and the conversion operator are implemented in terms of the same is_constructible template instantiation :(

This might not be a quick fix, I think I need to write a traits class and gradually filter out the options through multiple layers.
