### ISSUE TITLE
Eigen interopability missing digits, min_exponent, and max_exponent

### ISSUE THREAD

**Issue by FreddieWitherden** [boostorg/multiprecision#400]
The Eigen interoperability trait does not currently define the digits, min_exponent, and max_exponent methods.  However, these are required for norm calculation as can be seen here:

https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/StableNorm.h#L138

This results in compiler errors for any code which attempts to compute a norm of an Eigen vector/matrix parameterised by a multiprecision type.

**Comment by jzmaddock** [comment]
Looks like this requirement it was introduced in the last release.

Should be fixed, along with better testing in https://github.com/boostorg/multiprecision/pull/402

**Comment by jzmaddock** [comment]
Fixed in develop.
