### ISSUE TITLE
No Boost.Config for Standalone mode

### ISSUE THREAD

**Issue by c-lipka** [boostorg/multiprecision#442]
Despite the `readme.md` in version [boost-1.79.0.beta1](https://github.com/boostorg/multiprecision/releases/tag/boost-1.79.0.beta1) claiming that "Our package on this page already includes a copy of Boost.Config", that does not seem to be the case; at any rate, I can't find any sign of it in the zip archive downloaded from GitHub (or in the current master branch, for that matter).

If this is intentional, it would be helpful to rephrase the `readme.md`.

**Comment by mborland** [comment]
@NAThompson, @ckormanyos, @jzmaddock Now that 1.79 is on the streets can you cut a release that bundles standalone with config?

**Comment by jzmaddock** [comment]
Is there an "easy" way to do this that doesn't involve manually adding the libs/config/include files on a branch and then releasing that?  Or maybe that *is* the easy way!?  Otherwise we may need to come up with a script or something to simplify things...

**Comment by mborland** [comment]
I just cut the release for Boost.Math standalone 1.79. It looks like you'll have to manually add the files to the release. You could also try adding Boost.Config as a submodule to this one but I feel like that will cause other headaches.

**Comment by pdeitel** [comment]
Any updates on including boost/config.hpp in this standalone multiprecision instance?

**Comment by jzmaddock** [comment]
If you download the "official" release files then they do have Boost.Config included.  However, if you just grab the source then you will need to get Config separately.

**Comment by jzmaddock** [comment]
Which is to say this issue should be regarded as fixed by https://github.com/boostorg/multiprecision/releases.

I'll double check the readme file as well.

**Comment by pdeitel** [comment]
Is the official release a separate repository?
________________________________

**Comment by pdeitel** [comment]
﻿Thank you!

From: jzmaddock ***@***.***>
Date: Wednesday, August 31, 2022 at 1:10 PM
To: boostorg/multiprecision ***@***.***>
Cc: Paul Deitel ***@***.***>, Comment ***@***.***>
Subject: Re: [boostorg/multiprecision] No Boost.Config for Standalone mode (Issue #442)

Which is to say this issue should be regarded as fixed by https://github.com/boostorg/multiprecision/releases.

I'll double check the readme file as well.
