### ISSUE TITLE
Problem with comma as separator when reading a boost multiprecision rational number 

### ISSUE THREAD

**Issue by afabri** [boostorg/multiprecision#468]
When reading from a stream a rational number followed by a comma I get an error. This happens for the cpp as well as for the gmp backend.   I've put a gist [here](https://gist.github.com/afabri/b6543cce0a2da29219033bdce7719a43).    

When I put a blank before the comma it works (as the blank is then the delimiter".   I think the error is at [this line in number.hpp](https://github.com/boostorg/multiprecision/blob/develop/include/boost/multiprecision/number.hpp#L2322)

**Comment by afabri** [comment]
If I understand the code correctly I would add one more `case` for the rational numbers that is basically the same as for the integer numbers but adding the "/" to the matching character set:
```
case boost::multiprecision::number_kind_rational:
      if (oct_format)
         s = detail::read_string_while(is, "+-01234567/");
      else if (hex_format)
         s = detail::read_string_while(is, "+-xXabcdefABCDEF0123456789/");
      else
         s = detail::read_string_while(is, "+-0123456789/");
      break;
```

If that seems reasonable, I can make a pull request.

**Comment by jzmaddock** [comment]
This should be fixed in develop now.  I'll deal with octal and hex notation rationals separately.
