### ISSUE TITLE
Two unused variable warnings in function eval_convert_to misc.hpp using Visual Studio compiler

### ISSUE THREAD

**Issue by MonocleSecurity** [boostorg/multiprecision#473]
https://github.com/boostorg/multiprecision/blob/9f55ad5007cc5a041516da3b945901a53ba94023/include/boost/multiprecision/cpp_int/misc.hpp#L131

If the following BOOST_IF_CONSTEXPR(line 132) is false, then both variables "shift" and "i" are unused and produce warning C4189 using the Visual Studio 2019 compiler. When compiling with warnings as errors, this is a particularly annoying problem because you must disable warnings around every instance of the templated function.

I believe a simple solution is to move the two variables inside the if statement block and the functionality will remain the same.

**Comment by ckormanyos** [comment]
> a simple solution is to move the two variables inside the if statement block and the functionality will remain the same

Yep.

I ended up adding relevant changes form this issue and scanned all of Multiprecision for similar cases of scopes that can be reduced. Found about ten things at the end of it.

The changes, including those that handle this issue, are cycling in #471.
