### ISSUE TITLE
boost 1.70 multiprecision  does not work with 64 bit compiler under C++ builder 10.4

### ISSUE THREAD

**Issue by davidlewistoronto** [boostorg/multiprecision#493]
C++ builder community edition is 10.4 and can include boost 1.70. 32b compiles of multiprecision work but 64b do not. Example with some usual #includes not included. Perhaps 1.70 is obsolete but this is the only version that is available to C++ builder community edition. If any fix is known, such as compiling boost for C++ builder it would be appreciated. Link errors are:

[ilink64 Error] Error: Unresolved external '__udivti3' referenced from C:\USERS\DAVID\LOCAL_DEVEL\BOOST_TEST\WIN64\DEBUG\FILE1.O
[ilink64 Error] Error: Unresolved external '__umodti3' referenced from C:\USERS\DAVID\LOCAL_DEVEL\BOOST_TEST\WIN64\DEBUG\FILE1.O

      //---------------------------------------------------------------------------
      #include <boost/multiprecision/cpp_int.hpp>
      #include <boost/multiprecision/cpp_bin_float.hpp>
      #include <boost/rational.hpp>
      
      using namespace std;
      using namespace boost::multiprecision;
      using boost::rational;
      
      
      
      typedef boost::rational<cpp_int> t_prob;
      int main (int argc, char *argv [])
      {   t_prob a,b,c;
      
              a = 4;
      //      a /= 6;
              b = 13;
      //      b /= 7;
              c = a * b;
          std::cout << c << "\n";
      
      }

**Comment by jzmaddock** [comment]
I tried this with C++ Builder 10.4 update 2, and the latest Boost-1.80, and other than a warning about the compiler version being unknown, everything worked just fine in both 32 and 64 bit builds.

To test, I created a new GUI project using the default template, and just added your code to the form constructor, so the unit looks like:

```
#include <vcl.h>
#pragma hdrstop
#include "Unit1.h"
#include <boost/multiprecision/cpp_int.hpp>
#include <boost/multiprecision/cpp_bin_float.hpp>
#include <boost/rational.hpp>

using namespace std;
using namespace boost::multiprecision;
using boost::rational;

  //---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TForm1 *Form1;
//---------------------------------------------------------------------------
__fastcall TForm1::TForm1(TComponent* Owner)
	: TForm(Owner)
{
  typedef boost::rational<cpp_int> t_prob;
  t_prob a,b,c;

		  a = 4;
		  a /= 6;
		  b = 13;
		  b /= 7;
		  c = a * b;
}
```

What were the errors that you saw?

**Comment by jzmaddock** [comment]
Forgot to say, in the latest Boost code as a general point, cpp_rational is likely to be slightly more efficient than a boost::rational of cpp_int's.

**Comment by davidlewistoronto** [comment]
Thank you so much for replying. The errors are two link errors

[ilink64 Error] Error: Unresolved external '__udivti3' referenced from C:\USERS\DAVID\LOCAL_DEVEL\BOOST_TEST\WIN64\DEBUG\FILE1.O
[ilink64 Error] Error: Unresolved external '__umodti3' referenced from C:\USERS\DAVID\LOCAL_DEVEL\BOOST_TEST\WIN64\DEBUG\FILE1.O

 

I am forced to use 1.70 as that is what the GetIt manager provides. Can you please explain how to get 1.80? I’m using c++ builder community so they

may not make it easy to get the latest Boost.

 

Also thanks for the info about cpp_rational. I’ll have to try that.

 

Dave

**Comment by jzmaddock** [comment]
You can download the latest Boost release from www.boost.org, then just add the directory you extract that to to your #include path in the project options.

BTW I just tried some earlier versions of Boost and hit no end of errors, so I think upgrading is the way to go.

**Comment by davidlewistoronto** [comment]
Thanks for the help. I did consider that, but was afraid the binaries might not be compatible, and it might overwrite Embarcadaro’s.

If you have been successful, that sounds like the way to go.

 

Dave

**Comment by jzmaddock** [comment]
There are no binaries in the zip from the website, and in any case, Multiprecision is header only, no binaries required.  

If you need binaries for other libraries, then see https://www.boost.org/doc/libs/1_80_0/more/getting_started/windows.html but also in most cases, the libraries can be treated as "just a bunch of source files" and built as libraries from within your favorite IDE, or simply added direct to your application.

BTW we don't actually use or call the functions such as `__udivti3` that created your original linker errors, those function calls are generated by the compiler itself.

**Comment by davidlewistoronto** [comment]
Thanks again, I am just looking through the docs now.

**Comment by davidlewistoronto** [comment]
> There are no binaries in the zip from the website, and in any case, Multiprecision is header only, no binaries required.
> 
> If you need binaries for other libraries, then see https://www.boost.org/doc/libs/1_80_0/more/getting_started/windows.html but also in most cases, the libraries can be treated as "just a bunch of source files" and built as libraries from within your favorite IDE, or simply added direct to your application.
> 
> BTW we don't actually use or call the functions such as `__udivti3` that created your original linker errors, those function calls are generated by the compiler itself.

It takes nearly forever to unzip, but it works! Other than

[bcc64 Warning] codegear.hpp(19): boost: Unknown compiler version - please run the configure tests and report the results

which I can ignore or solve.

Thanks again.

**Comment by davidlewistoronto** [comment]
It works, after taking more than 30 minutes to unzip! Other than

 

[bcc64 Warning] codegear.hpp(19): boost: Unknown compiler version - please run the configure tests and report the results

 

which is unimportant and probably solveable.

 

Thanks again.
