### ISSUE TITLE
Add a forward declaration header.

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/multiprecision#508]
From ML question.  Seems reasonable.

**Comment by libbooze** [comment]
Hi @jzmaddock   thank you for opening the issue,
[here ](https://godbolt.org/z/r7qK65oaq)is how I have imagined it being used, lmk if that sounds implausible. 
If it does not great. :)

**Comment by shardator** [comment]
This would be very useful, some boost headers pull in a huge amount of code. For large projects this can increase compile times.
