### ISSUE TITLE
how to compile and run the tests

### ISSUE THREAD

**Issue by ofloveandhate** [boostorg/multiprecision#51]
i'd love to compile and run the tests for Boost.Multiprecision, but looking around, I don't see how to compile them.  I see `Jamfile.v2` in folder 📁 `test`, but invoking `b2` complains that it can't find `Jamfile.jam`...  my b2 version is `2015.07`.  looking for info indicated [how to do testing on the entirety of boost](http://www.boost.org/development/running_regression_tests.html), but what about just Multiprecision?

**Comment by NAThompson** [comment]
I do:

```
$ git clone --recursive https://github.com/boostorg/boost.git
$ cd boost; ./bootstrap; ./b2 --toolset=clang --compiler=clang++
$ cd libs/multiprecision/test
$ ../../../b2 --toolset=clang --compiler=clang++
```

My b2 breaks all the time, so I have to do a fresh clone.

**Comment by ofloveandhate** [comment]
thank you very much!  i think this is precisely what i wanted!

**Comment by ofloveandhate** [comment]
would you please take out the dollar signs from your shell commands?

**Comment by NAThompson** [comment]
Sure, but they are more expressions of intent than code . . .
