### ISSUE TITLE
All CI runs of type windows_msvc_14_0 for c++17 warn on not knowing c++17

### ISSUE THREAD

**Issue by ckormanyos** [boostorg/multiprecision#564]
ALL CI runs of type windows_msvc_14_0 for std C++17 warn that the toolset does not _know_ of C++17.

Each file reports somethnig like:

```
cl : Command line warning D9002 : ignoring unknown option `/std:c++17`
```

We should either give the compiler a standard that it _knows_ or use _latest_ or even remove the runs entirely?

Thoughts @jzmaddock and @mborland

**Comment by jzmaddock** [comment]
I think it should be /std:latest for C++17 on that compiler?
