### ISSUE TITLE
Type convertibility to `Backend` is assumed true if type is convertible to `number<Backend, et>`

### ISSUE THREAD

**Issue by oliverlee** [boostorg/multiprecision#608]
Hard error in default ops where a type `V` is assumed to be assignable to a backend type `B`. 

https://godbolt.org/z/ebEj5nzvh

**Comment by jzmaddock** [comment]
Confirmed, we're not differentiating between `number<>` is constructible from V because:

1) number<> has a suitable constructor, and
2) V has a conversion operator.

1) is handled, 2) is not and causes the error.  The easiest fix (to avoid exploding the number of operator overloads), might be to disallow 2) in mixed operations.  This also sort of feels like the right fix to me, what do folks think?

**Comment by ckormanyos** [comment]
> Confirmed, we're not differentiating between number<> is constructible from `V`

> The easiest fix (to avoid exploding the number of operator overloads), might be to disallow 2) in mixed operations. This also sort of feels like the right fix to me, what do folks think?

I played around with the overloads and found no simple fix. In the quickness of this issue, yes, a terse fix sounds better. If anything else breaks thereby, i do not know. This is an interesting case, which I had in another project and disregarded in basically the same way suggested by @jzmaddock.

**Comment by ckormanyos** [comment]
This stuff gets confusing when implicitly doing narrowing casts yet constructing works. It is sometimes tough to find exactly the right flavors of overloads. It's not really a help, but I've struggled whith this topic on several occasions.

Let it rip in CI and see, ... also with Math.

Cc: @mborland

**Comment by oliverlee** [comment]
I don't know what the implications would be allowing 2. and eager performing a conversion and then obtaining the backend. Disallowing 2. sounds reasonable - what would the new constraint would be?

For now, we specialize `is_compatible_arithmetic_type` to be `false`.

**Comment by oliverlee** [comment]
Also a better example of a wrapper type may be `std::reference_wrapper`

**Comment by jzmaddock** [comment]
This should now be addressed in develop - by addressed, I mean your example is still a compiler error because no operator overload is found, but it's the correct error now ;)
