### ISSUE TITLE
[Question] Simplifying a rational

### ISSUE THREAD

**Issue by sloriot** [boostorg/multiprecision#610]
Hi,

Is there a built-in method to simplify a rational? Calling gcd and doing the division of the numerator and denominator  is possible but while computing the gcd we should already have the simplified rational.

Thanks.

**Comment by jzmaddock** [comment]
The short answer is no, but I'm not quite sure what you're asking - for the ratio of two integers, the Euclid GCD algorithm doesn't compute the reduced terms just the common divisor.
