### ISSUE TITLE
nvc++ errors with message "float128_type is undefined"

### ISSUE THREAD

**Issue by davetaflin** [boostorg/multiprecision#640]
nVidia's HPC toolkit (https://developer.nvidia.com/hpc-sdk-downloads) supplies compiler nvc++, which defines macro __PGI. Using it to compiling a C++ file that #includes <boost/geometry/index/rtree.hpp> issues the following error message (this was with Boost 1.83.0, but the error began occurring with 1.79.0):

.../boost_1_83_0/boost/multiprecision/detail/number_base.hpp", line 205: error: identifier "float128_type" is undefined
  struct bits_of<float128_type>

Tested operating system: Ubuntu 20.04 LTS
Compiler: nvc++ 23.7-0 64-bit target on x86-64 Linux -tp haswell

**Comment by DJDavies2** [comment]
The code doesn't get as far as doing anything, the compilation fails just with the #include, e.g.:

`
#include <boost/multiprecision/float128.hpp>

int main()
{
}
`

**Comment by mborland** [comment]
This gets things compiling locally: https://github.com/boostorg/multiprecision/pull/641. Boost.Config says that the NVC++/PGI compiler should not be providing any kind of Float128 support. The NVC++ documentation only mentions `_Float128` in a bug fix so I assume this is still correct.

**Comment by DJDavies2** [comment]
Thanks, that fix seemed to work for me.
