### ISSUE TITLE
Construct from std::string_view

### ISSUE THREAD

**Issue by cos-public** [boostorg/multiprecision#66]
Would be handy. And from IEEE-754 (https://en.wikipedia.org/wiki/IEEE_754) decimals as well.

**Comment by ckormanyos** [comment]
I like the ideas, especiall potentially creating cpp_dec_float from IEEE-754 decimal type. At the moment, I do not have any experience with IEE-754 decimals, other than being vaguely aware of their specification. Thanks for the ideas, Chris.

**Comment by jzmaddock** [comment]
Waiting on https://github.com/boostorg/config/pull/239 before I can configure this.  Fortunately I know the library's author ;)

Re libDecimal: it's been on our TODO list from the start.  Hadn't realised that GCC supported the decimal number TR directly, will look into that.

**Comment by jzmaddock** [comment]
The string_view support is now in develop.

Closing as fixed, I've opened separate issues for decimal number support:

https://github.com/boostorg/multiprecision/issues/73
https://github.com/boostorg/multiprecision/issues/74
