### ISSUE TITLE
rvalue overload of backend()

### ISSUE THREAD

**Issue by johnmcfarlane** [boostorg/multiprecision#80]
Forgive my incomplete knowledge of value categories and your library types, but might [`backend()`](https://github.com/boostorg/multiprecision/blob/61f4fd8778074cbd78bceee739b5076846b75b23/include/boost/multiprecision/number.hpp#L711) benefit from a third overload taking an rvalue reference?

I've found these are useful for when the object is passed in in the form: `unwrap(some_object{})` and that in the body of the overloaded function, the returned value tends to be wrapped in a call to `std::forward<Backend>`. Without it, I suspect there are cases where a copy will be required where a move could be used instead. (However, I've not confirmed that this is best practice other than to ape some of the API of standard types such as `std::tuple`.)

**Comment by jzmaddock** [comment]
Might well be useful, let me experiment.  I assume you mean:

```
Backend&& backend()&&;
```
?

**Comment by johnmcfarlane** [comment]
Thanks. That's right, yes.

**Comment by johnmcfarlane** [comment]
thanks :)

**Comment by jzmaddock** [comment]
Just so you know - I only detected a couple of places in our code where that overload is called - and it made no difference in those particular cases - that's not to say it isn't the right thing to do though!
Probably only useful if you're calling backend() in your own code as ours typically handles rvalue-move semantics before it gets to that point (though there may be an opportunity to remove casts / simplify some code by relying on these new overloads).
