### ISSUE TITLE
`mpfr_const_bla` family of constants  🥧

### ISSUE THREAD

**Issue by ofloveandhate** [boostorg/multiprecision#81]
I sometimes need π.  I am not sure I trust the one in Boost.Math to provide π to arbitrary precision.  should i?  to be 100% confident, i petition for the exposure of `mpfr_const_pi` into Boost.Multiprecision.

**Comment by jzmaddock** [comment]
Yes Boost.Math constants are arbitrary precision, but in any case for performance reasons there are already specializations of the Math lib constants in mpfr.hpp for PI, euler, ln2 and catalan.  Which is to say that `boost::math::constants::pi<mpfr_float>() will call `mpfr_const_pi` already.
