### ISSUE TITLE
float128.hpp fails to compile with -std=c++17

### ISSUE THREAD

**Issue by plopresti** [boostorg/multiprecision#83]
Steps to reproduce:

1) #include <boost/multiprecision/float128.hpp>

2) Use GCC 7.x or 8.x

3) Compile with "g++ -std=c++17"

Result is various errors like this:

.../boost/multiprecision/float128.hpp:161:31: error: unable to find numeric literal operator \u2018operator""Q\u2019
          m_value = (f < 0) ? -1.0Q / 0.0Q : 1.0Q / 0.0Q;
                               ^~~~
.../boost/multiprecision/float128.hpp:161:31: note: use -fext-numeric-literals to enable more built-in suffixes

Compiling with "-fext-numeric-literals" (as the error message suggests) or with "-std=gnu++17" makes the problem go away.

I am not sure whether this is user error, or if there a more standards-compliant way to create quad-precision constants...

**Comment by NAThompson** [comment]
This is not specific to C++17; you must always compile with `-fext-numeric-literals` to get the quad precision constants to work.

**Comment by plopresti** [comment]
True, but I do not need quad-precision constants to work; I need Boost.Multiprecision to work.

Note that `-fext-numeric-literals` is the default for `-std=c++03` (and earlier) because extended literals cannot break standards-conforming code prior to C++11.

This is the first example I know of a Boost library that requires a standards-breaking compiler option to use at all. Is there really no way to rewrite this in a standard-conforming way (with all of C++11's user-defined literals and `constexpr` and so on)? Or is that not a worthwhile goal?

I admit this is a minor thing, but it is a thing.

**Comment by jzmaddock** [comment]
Actually it needs `-std=gnu++11/14/17`.  The issue being that the implementation relies entirely on GNU specific extensions - `__float128` etc.
The rest of the library most certainly is usable in strictly standards conforming mode, just not that one header.  Using user-defined literals is an interesting idea, but a fair bit of work...

Closing as the header works as we intended it to.  While we're at it it's also worth pointing out that float128.hpp is only compilable by gcc or Intel, not clang or msvc.

**Comment by plopresti** [comment]
Actually `__float128` and related functionality still works with `-std=c++11` etc. The `-std=c++NN` switches do not disable all GNU extensions; only the ones that can break standard-conforming code. For `float128.hpp`, the only thing that stops working are the quad-precision literals. Everything else still works fine.

So this bug is perhaps not quite as silly as you think.
