### ISSUE TITLE
is there a list of projects using Boost.Multiprecision?

### ISSUE THREAD

**Issue by ofloveandhate** [boostorg/multiprecision#85]
I have found it nice with other libraries to have some idea of what projects use them.  Is there a list for Boost.Multiprecision?  I looked and failed to find.

**Comment by jzmaddock** [comment]
No.

I do know that there are plenty of bug-reports quickly arriving if we make a mistake so someone other than yourself must be using it ;)

**Comment by NAThompson** [comment]
There is a list of public clones under the insights tab. This shows how many people are doing clones of the head and the referrer header, which gives a partial answer to your question.

**Comment by jzmaddock** [comment]
I suspect most of those clones are folks working on the whole boost tree?  Most users probably wouldn't get the library that way.

**Comment by NAThompson** [comment]
I think you are right; I compared the clones for boost.math with boost.multiprecision, and they are almost perfectly correlated.

The referrer header might be more interesting? I note that https://advanpix.com/ is showing up a lot; maybe that is the one project using boost.math and boost.multiprecision?

**Comment by jzmaddock** [comment]
>I note that https://advanpix.com/ is showing up a lot; maybe that is the one project using boost.math and boost.multiprecision?

Not sure about those guys - they have contributed patches to Math, but I think they use us as a benchmark to compare their proprietary code against.

**Comment by johnmcfarlane** [comment]
I do value knowing what else uses a library. It can provide good usage
examples.

CNL uses Multiprecision for testing interop.
