### ISSUE TITLE
cpp_int.hpp, unused parameter warning in clang

### ISSUE THREAD

**Issue by HDembinski** [boostorg/multiprecision#92]
cpp_int.hpp:833
`BOOST_MP_FORCEINLINE void resize(unsigned new_size, unsigned min_size)`

raises a warning on clang compilers, since new_size is not used inside the function. Please change this to

`BOOST_MP_FORCEINLINE void resize(unsigned /* new_size */, unsigned min_size)`

**Comment by jzmaddock** [comment]
Closing in favour of the PR.
