### ISSUE TITLE
Multiprecision Complex: to_string() overload?

### ISSUE THREAD

**Issue by NAThompson** [boostorg/multiprecision#97]
Would implementing `to_string()` for complex multiprecision numbers be a nice roundout of the feature set?

**Comment by jzmaddock** [comment]
There's a str() member function already, or did you mean implement a version of std::to_string?  The latter seems to have rather unexpected behaviour?

**Comment by NAThompson** [comment]
I meant to implement a version of `std::to_string` using ADL, something like `std::string to_string(complex128 z) { return z.str(); }`.

Then people would be able to write `std::string msg = "Error: z = " + to_string(z);`.

Would this be useful/worth the effort?

**Comment by jzmaddock** [comment]
Nod.  On reflection it does help with generic code.  You would need to play with precision and format flags a little to match the behaviour of the std version, but in principle would it just be the same as:

```
template <class Backend, expression_template_option ExpressionTemplates>
std::string to_string(const number<Backend, ExpressionTemlates>& val)
{
  return val.str(6, std::ios_base::fixed|std::ios_base::showpoint);
}
```

?

**Comment by NAThompson** [comment]
Just looked up the definition of `to_string()` [here](http://www.cplusplus.com/reference/string/to_string/):

> As many digits are written as needed to represent the integral part, followed by the decimal-point character and six decimal digits.
inf (or infinity) is used to represent infinity.
nan (followed by an optional sequence of characters) to represent NaNs (Not-a-Number).
The representations of negative values are preceded with a minus sign (-).

So it looks like your code is correct, though you could argue that this is a pretty bizarre spec (which I hadn't realized before opening this issue).

**Comment by agurtovoy** [comment]
The cplusplus.com definition is somewhat incorrect; for all the numeric `to_string` overloads, the standard simply says (24.3.4.7 [string.conversions]):

*Returns*: Each function returns a string object holding the character representation of the value of its argument that would be generated by calling `sprintf(buf, fmt, val)` with a format specifier of `"%d"`, `"%u"`, `"%ld"`, `"%lu"`, `"%lld"`, `"%llu"`, `"%f"`, `"%f"`, or `"%Lf"`, respectively, where `buf` designates an internal character buffer of sufficient size.

My guess is that the "followed by the decimal-point character and six decimal digits" part of the cplusplus.com definition comes from [`sprintf`](https://en.cppreference.com/w/cpp/io/c/fprintf) `"%f"` spec, which sets the default precision for _floats_ to 6 (which makes sense for floats).

IOW, I don't think the standard's definition binds you to force the 6 digit precision here, and I'd argue it'd be in the spirit of the standard's definition to set the default precision to whatever makes sense for each particular type.

**Comment by jzmaddock** [comment]
Can this be closed now?
